language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php bin/coveralls -v

notifications:
    email:
        - lebrun.k@gmail.com
